### ISSUE TITLE
Roadmap to MVP

### ISSUE THREAD

**Issue by jasonlally** [DataSF/open-data-explorer#1]
I'll flesh this out some more, but wanted to get a draft roadmap going so we can track overall progress. I'll also link to all of the collateral (wireframes, design specs as needed) for reference. This is just a list, we'll track the order/priority of these using issues and Zenhub.
# Feature breakdown
## Home page
- [ ] Create home page structure/scaffolding
- [ ] Build search component with autosuggestions
## Dataset catalog search
- [ ] Finish fine design on dataset cards
- [ ] Finish fine design on facets
- [ ] Determine data structure, fields and approach for loading datasets into search index
## Dataset explorer
- [ ] Finish fine design on persistent dataset information (title, description, basic metadata fields)
- [ ] Create persistent related datasets footer just above site footer
- [x] Create tab for dataset overview
- [x] Create tab for dataset details
- [x] Create tab for charts
- [ ] Create tab for map
- [x] Create tab for table preview

The following break down the dataset explorer into chunks of features
### Related datasets
- [ ] Develop approach to surfacing related datasets using existing infrastructure
- [ ] Create components that show related datasets by certain dimensions (department, program (tag), etc.)
### Overview
- [ ] Create chart card component
- [ ] Design parameterized URL structure for use in embeddable charts
### Dataset Details
- [ ] Develop component containing full metadata, including attachments when present
- [ ] Develop field definition cards including name, type, stats based on type
- [ ] Investigate Desk.com API
- [ ] Develop component that shows any related knowledge base articles, if any
### Charts
- [x] Rethink/redesign state and props for charts overall (evaluate what we really need in state, the structure of that, and introduce validated prop types)
- [ ] Improve UI interaction for comparing one category against the rest
- [x] Create filter type: numeric
- [x] Create filter type: category
- [x] Create filter type: boolean
- [x] Create filter type: date/time
- [x] Develop filter selector + interaction
- [ ] Develop legend component and place above chart - remove embedded legend
- [ ] Develop dynamic titles/subtitles based on filters
- [ ] Add clear x/y axes to charts
- [ ] Add formatting filter for different numeric types ($, thousands separator, etc)
- [ ] Add date/time fields to group by options
- [ ] Develop group by transform for category vs. category field types
- [ ] Add aggregation options where numeric types exist - sum, count
- [ ] Create embed button component with easy copy link, simple JIT help content, and links to knowledge base articles as necessary (use in other components)
- [ ] Introduce color into the column buttons to differentiate among column types
- [ ] Create table option for charts and toggle bw table/chart
- [ ] Hour, day, month, year toggles
- [ ] Create sort by options for boolean charts (sort by total, sort by true, sort by false)
### Embeds
- [ ] Develop embed component that reuses the charting components and accepts parameters from url
### Map
- [ ] Develop approach to thematic mapping where a column exists representing the boundary
- [ ] Develop approach to point-based maps
- [ ] Develop approach to basic mapping of data stored as lines and polygons
- [ ] Develop component that provides information to user on click of map feature
- [ ] Develop component that allows searching by address
- [ ] Develop basic query by radius and export to...functions (based on pd prototype)
### Table Preview
- [ ] Provide clearer UI indicator for sorting
- [ ] Reuse field definition card component for on hover interaction for fields to provide JIT information
