### ISSUE TITLE
As a user, I want to give feedback and report bugs

### ISSUE THREAD

**Issue by jasonlally** [DataSF/open-data-explorer#296]
**User story**
Users want to have easy ways to tell us what they like, what they don't like and what's not working to contribute to the success of the application. We also want this, more feedback means more data for us to base our roadmap planning on.

**Acceptance criteria**
- [x] A button, link or other component to access feedback in an accessible place
- [x] Options to submit bugs or feedback through a simple form
- [x] A single place (db, google sheet, etc.) for that feedback to go
- [x] Automatically collect user agent information and page state for debugging when reporting bugs

**Definition of done**
User can successfully find and submit feedback and bugs to us.

**Tasks**
- [x] Research form options that can meet the above criteria (types, automatic population of fields, writes to standard location where we can easily access data)
- [x] Develop feedback component
- [ ] Develop components to encapsulate the form (modal or page)
- [ ] Accessibility testing for forms and button

**Comment by jasonlally** [comment]
Probably simplest to create a custom form in react and post data to google sheets:
https://stackoverflow.com/questions/21102684/google-forms-send-data-to-spreadsheet

http://jamesknelson.com/learn-raw-react-ridiculously-simple-forms/

**Comment by jasonlally** [comment]
Addressed by #311
