### ISSUE TITLE
Identify metrics and implement event tracking in google analytics to capture where possible

### ISSUE THREAD

**Issue by jasonlally** [DataSF/open-data-explorer#386]
Added analytics events in the middleware and added a ga object to any action we want to process as an event.

This should be a scalable, transparent solution to tracking events in the app.

- [x] Outbound link to API docs
- [x] Select field to create chart
- [x] Select chart type
- [x] Add filter
- [x] Apply filter options
- [x] Select field to group by
- [x] Select field to sum by
- [x] Download data
- [x] Select field in the field definitions
- [x] Filter list of fields by type
- [x] Click sharing link
- [x] Click "Copy" button on share modal
- [x] Search from autocomplete
